version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/python:3.10.6
    steps:
      - checkout

      # Step to install dependencies
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt

      # Step to run tests with coverage
      - run:
          name: Run Tests with Coverage
          command: |
            pytest --cov=src
